export default class Constants {
    static FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
    static FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS';
    static FETCH_COMMENTS_LIST = 'FETCH_COMMENTS_LIST';
    static POST_COMMENT = 'POST_COMMENT';
    static DELETE_COMMENT = 'DELETE_COMMENT';
    static EDIT_COMMENT = 'EDIT_COMMENT';
    static MAKE_COMMENT_EDITABLE = 'MAKE_COMMENT_EDITABLE';
}